---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    51.140.77.31:
      ansible_user: 'adminuser12'
      ansible_password : 'P@$$word1234!'
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_server_cert_validation: ignore

...
