---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    137.116.232.58:
      ansible_user: 'ansible'
      ansible_password : 'Testpassword1234!'
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_server_cert_validation: ignore

...
